# Generated by Django 3.2.3 on 2021-05-29 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_district_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(auto_now_add=True)),
                ('update_time', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('username', models.CharField(max_length=50)),
                ('chat_id', models.CharField(max_length=20)),
                ('saved_alerts', models.JSONField(null=True)),
                ('recent_searches', models.JSONField(null=True)),
                ('alerts_18', models.PositiveIntegerField(default=0)),
                ('alerts_45', models.PositiveIntegerField(default=0)),
                ('total_alerts_18', models.PositiveIntegerField(default=0)),
                ('total_alerts_45', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name_plural': 'District'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'verbose_name_plural': 'State'},
        ),
    ]
