# Generated by Django 3.2.3 on 2021-05-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210529_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='recent_searches',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='saved_alerts',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
